SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS MAX_FAV
ON R.FOOD_TYPE = MAX_FAV.FOOD_TYPE
AND R.FAVORITES = MAX_FAV.FAVORITES
ORDER BY R.FOOD_TYPE DESC;
